### ISSUE TITLE
Very nice

### ISSUE THREAD

**Issue by diegosaul402** [UlisesAC4/firstAssignment#1]
Hi Ulises,
Your page is great I like the clean design you use, the colors are nice and seems response very well to different screen sizes. Except by the menu.
![image](https://cloud.githubusercontent.com/assets/14918730/23110834/e451da1c-f6e9-11e6-90b7-cf01f674ded9.png)
The footer gets as well very big with small window size.
I didn't notice you use tabs on your hobbies section until saw your code, maybe need to be more visible.
You taught me a new framework I did not know and looks good. Greetings.

**Comment by ulisesac4** [comment]
I never thought about mobile design and you have showed me an issue with the framework, after all this framework is suposed to follow material design guidelines and the recomended navbar seems to be the vertical one as a google app.

For the moment it seems more viable to just change to a vertical navbar, about the footer I will have to look closely by my self to see how change it. And for the tabs this framework is very minimalistic so it shows and underscore in the active tab (which at the moment was not able to change its color because I need to use sass variables and was not at the mood of doing it)

**Comment by ulisesac4** [comment]
The navbar is already fixed, about the footer there is no other way to represent it, so for now it will be like that, thank your for your comments :)
