### ISSUE TITLE
Nice page

### ISSUE THREAD

**Issue by kerbero1994** [UlisesAC4/firstAssignment#8]
Hello, good evening, well the page contains some areas of opportunity such as including the fav-icon and smoothing the transitions between sections when making use of the menu, besides including some photo, space management, and color management is good, nice work.

**Comment by ulisesac4** [comment]
I was against adding JS code that a priori was not able to understand, that is way I left it like it is now, it is interesting talking about the fav icon because I feel that it is not needed for now. About the photo I tried to put it but was not able to centered on the header so I discarded it thank you :)
